[build]
  command = "rm -rf node_modules/.bin/vite && npm install && npx vite build"
  publish = "dist"
  functions = "../netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
